### ISSUE TITLE
Is this repository in beta status?

### ISSUE THREAD

**Issue by sudoman** [DavidGriffith/inform6unix#9]
I'm planning on packaging inform 6 for Fedora. (Note that I'm new to this, but I have a mentor.)

It's my understanding that Fedora only distributes stable releases of software. Is this repository in beta or is it a stable release? I ask because I see a `-b3` at the end of the latest git tag version number.

**Comment by sudoman** [comment]
My mentor said that this repo should be good to go, so no worries about the `-b3` flag. : )

**Comment by DavidGriffith** [comment]
Please don't package this up quite yet.  I'm waiting until I fix one more bug in the Inform Library.  I'll post here again when I'm done with that.

**Comment by sudoman** [comment]
I'm happy to wait for the next git tag, as the prior autotools setup is somewhat broken and I don't really want to dive into that. : )

**Comment by sudoman** [comment]
Is this project ready for packaging now that there's a git tag for commit 5231323e859e868bb751614d8f0220e0dff15111?

**Comment by DavidGriffith** [comment]
Sorry, I forgot about this Issue.  Inform6unix is ready for widespread use.  It might be more useful for you to take a tarball from here instead of the IF Archive.  Right now it's takes a long time for something to work its way from the unprocessed/ directory to where it needs to go.

Something I forgot to do in the Makefile was to have it install the contents of contrib/.  The two Perl scripts (pblorb.pl and scanblorb.pl) there are necessary for packing up sound and graphics resources into Blorb files.  That is the only mechanism supported these days for sound and graphics by Z-machine and Glulx interpreters.  I'd very much appreciate it if you'd have your RPM install those two scripts.
